version: '3.6'

services:
  web:
    build: .
    image: grokmycode
    command: python ./grokmycode/manage.py runserver 0.0.0.0:8000 --settings=grokmycode.settings.dev
    ports:
      - 8000:8000
    volumes:
      - .:/code